name:                arbor-monad-metric
version:             0.0.1
github:              "arbor/arbor-monad-metric"
license:             MIT
category:            Services
author:              Arbor Networks
maintainer:          mayhem@arbor.net
copyright:           Arbor Networks

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on Github at <https://github.com/arbor/arbor-monad-metric#readme>

default-extensions:
- BangPatterns
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- MultiParamTypeClasses
- OverloadedStrings
- TupleSections

dependencies:
- base >=4.7 && <5
- bytestring
- containers
- generic-lens
- lens
- mtl
- network
- stm
- resourcet
- transformers

- arbor-datadog
- text

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints

tests:
  arbor-monad-metric-test:
    main:                Spec.hs
    source-dirs:
    - test
    - src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - arbor-monad-metric
    - hspec
    - hedgehog
    - hw-hspec-hedgehog
